version: '3.8'

services:
  random-pic-service:
    build: . # 从当前目录的 Dockerfile 构建
    container_name: my_random_pic
    ports:
      - "17777:17777"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./local_images:/app/local_images  # 绑定挂载本地目录
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/random_pic_db?sslmode=disable
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme

  db:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=random_pic_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # 仅保留必要卷
